name: "About Paneldata"
markdown: "kramdown"
highlighter: true
encoding: "utf-8"
defaults:
  -
    scope:
      path: ""
    values:
      author: "Marcel Hebing"
      layout: "default"
  -
    scope:
      path: "imports"
    values:
      layout: "imports"
kramdown:
  input: "GFM"
  hard_wrap: false
